server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    enabled: false
  data:
    mongodb:
      uri: "mongodb+srv://jcardozop:G6UcSkdEtDfa@cluster0.7gvp1tj.mongodb.net/?retryWrites=true&w=majority"
      database: Auth

